// Generated by CoffeeScript 1.6.1
(function() {
  var makeActive;

  _.templateSettings = {
    interpolate: /\{\{(.+?)\}\}/g,
    evaluate: /\{\%(.+?)\%\}/g
  };

  makeActive = function(i, el) {
    var $el;
    $el = $(el);
    return console.log($el.data());
  };

  $('.AMDElement').each(makeActive);

}).call(this);
