_ = require 'underscore'

_.templateSettings =
  interpolate : /\{\{(.+?)\}\}/g
  evaluate : /\{\%(.+?)\%\}/g

module.exports = _.template """<!--
This file was generated by Active Markdown, v{{ VERSION }} - http://activemarkdown.org

{{ input_file_name }} - {{ now }}
-->
<!DOCTYPE html>
<html>
    <head>
        <title>{{ title }}</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        {{ styles }}
    </head>
    <body>
        <div id="AMContent">
            {{ markup }}
        </div>
        {{ scripts }}
    </body>
</html>
"""